ballerina/Ballerina.toml
ballerina/Dependencies.toml
ballerina/build.gradle
ballerina/tests/MedicalItemClient.bal
build-config/resources/Ballerina.toml
build.gradle
gradle.properties

Fix build failure

---

ballerina/sql_client.bal
ballerina/tests/basic-tests.bal
ballerina/tests/composite-keys-test.bal
ballerina/tests/department_client.bal
ballerina/tests/entities.bal
ballerina/tests/init-tests.bal
ballerina/tests/medicalitem_client.bal
ballerina/tests/resources/sql-scripts/init.sql

$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3215

Add support for composite keys

---

ballerina/Dependencies.toml
ballerina/sql_client.bal
ballerina/tests/basic-tests.bal
ballerina/tests/department_client.bal
ballerina/tests/medicalitem_client.bal
ballerina/tests/medicalneed_client.bal
examples/medical-center/medicalitem_client.bal
examples/medical-center/medicalneed_client.bal

$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3243

Add complex data-type retrieval support for read()

---

ballerina/sql_client.bal
ballerina/tests/basic-tests.bal
ballerina/tests/medicalitem_client.bal
ballerina/tests/medicalneed_client.bal

$subject for the use of "Advanced query" feature
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3304
Fixes:
N/A

Introduce execute API and improve read APIs

---

ballerina/Dependencies.toml
ballerina/sql_client.bal
ballerina/tests/basic-tests.bal
gradle.properties

Fix execute method in persist client

---

docs/proposals/support_advanced_filter_conditions.md

$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3303
N/A

Add advanced filter condition support proposal

---

compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/PersistGenerateSqlScript.java

$Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3421

Update the newline character based on OS

---

ballerina/Ballerina.toml
ballerina/build.gradle

Fix docker failure in Mac M1

---

ballerina/tests/associations_test.bal
ballerina/tests/company_client.bal
ballerina/tests/department_client.bal
ballerina/tests/employee_client.bal
ballerina/tests/multipleassociations_client.bal
ballerina/tests/profile_client.bal
ballerina/tests/user_client.bal

$subject
Related to: https://github.com/ballerina-platform/ballerina-standard-library/issues/3454

Update clients with read() and execute() APIs and streams

---

examples/medical-center/Ballerina.toml
examples/medical-center/Config.toml
examples/medical-center/README.md
examples/medical-center/entities.bal
examples/medical-center/main.bal
examples/medical-center/modules/clients/database_configuration.bal
examples/medical-center/modules/clients/entities.bal
examples/medical-center/modules/clients/medicalitem_client.bal
examples/medical-center/modules/clients/medicalneed_client.bal

Redo the example with latest changes and include README file

---

README.md
ballerina/Package.md

Add base README content

---

examples/medical-center/README.md

Update README.md file

---

build.gradle
gradle.properties

Rename properties to indicate test dependencies

---

gradle.properties

Update dependencies to latest snapshot version

---

ballerina/sql_client.bal

$subject
This is required as this method is used in the generated clients

Make `getManyRelations()` method public

---

.github/workflows/pull-request.yml
ballerina/Dependencies.toml
gradle.properties

Migrate to Ballerina Update 4

---

ballerina/sql_client.bal

Remove unnecessary cloneWithType()

---

compiler-plugin-test/src/test/java/io/ballerina/stdlib/persist/compiler/CodeModifierTest.java
compiler-plugin-test/src/test/java/io/ballerina/stdlib/persist/compiler/plugin/CompilerPluginTest.java
compiler-plugin-test/src/test/resources/test-src/plugin/package_12/Ballerina.toml
compiler-plugin-test/src/test/resources/test-src/plugin/package_12/sample.bal
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/Constants.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/DiagnosticsCodes.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/PersistRecordValidator.java

$Subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3682

Improve the impl to allow  the explicit initialisation in the annotation

---

ballerina/tests/associations_test.bal
ballerina/tests/basic-tests.bal
ballerina/tests/company_client.bal
ballerina/tests/complextype_client.bal
ballerina/tests/department_client.bal
ballerina/tests/employee_client.bal
ballerina/tests/medicalitem_client.bal
ballerina/tests/medicalneed_client.bal
ballerina/tests/multipleassociations_client.bal
ballerina/tests/profile_client.bal
ballerina/tests/user_client.bal
compiler-plugin-test/src/test/resources/testng.xml
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/PersistCompilerPlugin.java
examples/medical-center/modules/clients/medicalitem_client.bal
examples/medical-center/modules/clients/medicalneed_client.bal

$subject
Related to  https://github.com/ballerina-platform/ballerina-standard-library/issues/3576#issuecomment-1333487930

Remove advance filter query support for phase 1

---

compiler-plugin-test/src/test/java/io/ballerina/stdlib/persist/compiler/plugin/CompilerPluginTest.java
compiler-plugin-test/src/test/resources/test-src/plugin/package_32/Ballerina.toml
compiler-plugin-test/src/test/resources/test-src/plugin/package_32/sample.bal
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/DiagnosticsCodes.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/PersistCodeAnalyzer.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/PersistRecordValidator.java

$Subject
Fixes:
https://github.com/ballerina-platform/ballerina-standard-library/issues/3492
https://github.com/ballerina-platform/ballerina-standard-library/issues/3680

Improve the compiler plugin validation to fix the detected issues

---

compiler-plugin-test/src/test/java/io/ballerina/stdlib/persist/compiler/plugin/CompilerPluginTest.java
compiler-plugin-test/src/test/resources/test-src/plugin/package_33/Ballerina.toml
compiler-plugin-test/src/test/resources/test-src/plugin/package_33/sample.bal
compiler-plugin-test/src/test/resources/test-src/plugin/package_34/Ballerina.toml
compiler-plugin-test/src/test/resources/test-src/plugin/package_34/sample.bal
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/Constants.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/DiagnosticsCodes.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/PersistRecordValidator.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/models/Entity.java

$Subject
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/3816

Add validations for not allowable record field types

---

compiler-plugin-test/src/test/java/io/ballerina/stdlib/persist/compiler/plugin/CompilerPluginTest.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/Constants.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/PersistRecordValidator.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/Utils.java

$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3831

Remove usages of toSourceCode()

---

compiler-plugin-test/src/test/java/io/ballerina/stdlib/persist/compiler/plugin/CompilerPluginTest.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/Constants.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/DiagnosticsCodes.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/PersistRecordValidator.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/models/Field.java

$subject
Part of https://github.com/ballerina-platform/ballerina-standard-library/issues/3765

[Phase 2] Refactor and simplify compiler validations

---

ballerina/annotation_types.bal
ballerina/tests/entities.bal

Fix test cases with optional relation fields

---

compiler-plugin-test/src/test/resources/test-src/plugin/package_24/sample.bal
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/Constants.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/PersistRecordValidator.java

Add support for byte[] field type

---

compiler-plugin-test/src/test/java/io/ballerina/stdlib/persist/compiler/CompilerPluginTest.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/DiagnosticsCodes.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/PersistRecordValidator.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/models/Field.java

$subject
Related to: https://github.com/ballerina-platform/module-ballerina-persist/pull/85
Fixes https://github.com/ballerina-platform/ballerina-standard-library/issues/3883

[Phase 3] Add support for optional @Relation annotation attachment

---

ballerina/Dependencies.toml
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/PersistRecordValidator.java
gradle.properties

Fix diagnostic location for 1:1 relation w/o annotation

---

compiler-plugin-test/src/test/java/io/ballerina/stdlib/persist/compiler/CompilerPluginTest.java
compiler-plugin-test/src/test/resources/test-src/project_2/persist/field-types.bal
compiler-plugin-test/src/test/resources/test-src/project_2/persist/invalid-relation.bal
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/DiagnosticsCodes.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/PersistModelDefinitionValidator.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/Utils.java

Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/3926

Improve validations for Entity Definition Model

---

ballerina/sql_client.bal
ballerina/tests/generated_client.bal

Add `AbstractPersistClient` class again

---

compiler-plugin-test/src/test/java/io/ballerina/stdlib/persist/compiler/CompilerPluginTest.java
compiler-plugin-test/src/test/resources/test-src/project_2/persist/optional-association.bal
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/DiagnosticsCodes.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/PersistModelDefinitionValidator.java

$subject
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3926

Validate nillable type in associated fields

---

ballerina/tests/generated_client.bal
ballerina/tests/generated_types.bal
ballerina/tests/init-tests.bal
ballerina/tests/persist/rainier.bal
ballerina/tests/resources/sql-scripts/init.sql

This PR re-orders the entities used in the test cases to bring them in-line with how the client and type generation scripts work.

Re-order entities

---

ballerina/errors.bal
ballerina/metadata_types.bal
ballerina/sql_client.bal
ballerina/utils.bal
gradle.properties

Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4007

Tweak api docs of public functions, types and errors

---

README.md
ballerina/Module.md
ballerina/Package.md

Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4007

Add module, package description files

---

compiler-plugin-test/src/test/java/io/ballerina/stdlib/persist/compiler/CompilerPluginTest.java
compiler-plugin-test/src/test/resources/test-src/project_2/persist/usage-of-escape-characters.bal
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/PersistModelDefinitionValidator.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/Utils.java
docs/spec/spec.md

Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4016

Fix validations not taking into account escape character

---

compiler-plugin-test/src/test/java/io/ballerina/stdlib/persist/compiler/CompilerPluginTest.java
compiler-plugin-test/src/test/resources/test-src/project_2/persist/usage-of-escape-characters.bal
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/PersistModelDefinitionValidator.java

$subject (Revisit once https://github.com/ballerina-platform/ballerina-lang/issues/39441 is resolved)
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/4016

[Temporary] Take into account escape characters for ballerina types

---

compiler-plugin-test/src/test/java/io/ballerina/stdlib/persist/compiler/CompilerPluginTest.java
compiler-plugin-test/src/test/resources/test-src/project_2/persist/usage-of-import-prefix.bal
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/DiagnosticsCodes.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/PersistCodeAnalyzer.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/PersistModelDefinitionValidator.java

Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4023

Validate the usage of import prefix

---

compiler-plugin-test/src/test/java/io/ballerina/stdlib/persist/compiler/CompilerPluginTest.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/DiagnosticsCodes.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/PersistModelDefinitionValidator.java

Rearrange grouping of diagnostic codes as per related context

---

compiler-plugin-test/src/test/java/io/ballerina/stdlib/persist/compiler/CompilerPluginTest.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/DiagnosticsCodes.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/PersistModelDefinitionValidator.java

Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4017

Improve diagnostic messages

---

.github/workflows/build-with-bal-test-native.yml
README.md
gradle.properties

Add graalvm check
Fixes: https://github.com/ballerina-platform/ballerina-standard-library/issues/3481

Add graalvm check

---

ballerina/Module.md
docs/spec/spec.md

Update the equivalent MySQL type for float and decimal ballerina type

---

.github/workflows/publish-release.yml

Fix GH release and sync PR title

---

.github/pull_request_template.md
.github/workflows/pull-request.yml

$subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4098

Add codecov token to the pr check

---

.github/workflows/build-timestamped-master.yml

$subject. This is a temp fix. we are maintaining separate branch for the feature

[temp fix] add new branch to build timestamp workflow

---

.github/workflows/build-timestamped-master.yml

Change the publishing task to push only to github packages

---

.github/workflows/build-timestamped-master.yml

Fix build workflow

---

ballerina/Dependencies.toml
ballerina/sql_client.bal
ballerina/tests/all-types-tests.bal
ballerina/tests/associations-tests.bal
ballerina/tests/workspace-tests.bal
ballerina/types.bal
examples/medical-center/generated/generated_client.bal
native/src/main/java/io/ballerina/stdlib/persist/QueryProcessor.java
native/src/main/java/io/ballerina/stdlib/persist/Utils.java

$subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/4087

Fix error when partial associations are retrieved

---

.github/workflows/publish-release.yml

Temporary remove ballerina lang version split logic

---

examples/build-config/medical-center/Ballerina.toml
examples/build.gradle

Update build scripts to example toml file versions automatically

---

.github/workflows/build-timestamped-master.yml
.github/workflows/publish-snapshot-nexus.yml

Ensure tests are run before publish

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
examples/medical-center/Ballerina.toml
gradle.properties

Update to latest Update 5 timestamped version

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
examples/medical-center/Ballerina.toml
gradle.properties

Update dependency versions for update 5

---

ballerina/utils.bal

Make filterRecord method public

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
examples/medical-center/Ballerina.toml
native/src/main/java/io/ballerina/stdlib/persist/Utils.java
native/src/main/java/io/ballerina/stdlib/persist/datastore/MySQLProcessor.java

Implement fix for https://github.com/ballerina-platform/ballerina-standard-library/issues/4333 to 0.3.0 release branch for new release

Correct usage of invokeMethodAsyncSequentially()

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
ballerina/Module.md
docs/spec/spec.md
examples/medical-center/Ballerina.toml

$Subject
Related to https://github.com/ballerina-platform/ballerina-standard-library/issues/4370

Update API doc and spec with default MySQL type for ballerina byte[]

---

build.gradle
gradle.properties

Add crypto dependency

---

ballerina/Dependencies.toml
ballerina/tests/in_memory_rainer_generated_client.bal
ballerina/tests/in_memory_test_entities_generated_client.bal
ballerina/tests/sql_rainier_generated_client.bal
ballerina/tests/sql_test_entities_generated_client.bal
ballerina/utils.bal

$subject 
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/4393

Make generated clients isolated

---

.github/workflows/build-timestamped-master.yml
.github/workflows/build-with-bal-test-native.yml
.github/workflows/central-publish.yml
.github/workflows/publish-release.yml
.github/workflows/publish-snapshot-nexus.yml
.github/workflows/pull-request.yml

Update workflows to include github secrets for auth

---

ballerina/in_memory_client.bal
ballerina/metadata_types.bal

$subject
Related issue: https://github.com/ballerina-platform/ballerina-lang/pull/40410#issuecomment-1545431140

Make in-memory query functions isolated

---

ballerina/in_memory_client.bal

$subject
Related issue: https://github.com/ballerina-platform/ballerina-lang/pull/40410

Fix invalid invocation of non-isolated function in an isolated function

---

ballerina/errors.bal
ballerina/googlesheets_client.bal
ballerina/in_memory_client.bal
ballerina/metadata_types.bal
ballerina/sql_client.bal
ballerina/tests/googlesheets_rainier_generated_client.bal
ballerina/tests/gsheets-building-tests.bal
ballerina/tests/gsheets-composite-key-tests.bal
ballerina/tests/gsheets-department-tests.bal
ballerina/tests/gsheets-employee-tests.bal
ballerina/tests/gsheets-workspace-tests.bal
ballerina/tests/in-memory-all-types-tests.bal
ballerina/tests/in-memory-building-tests.bal
ballerina/tests/in-memory-composite-key-tests.bal
ballerina/tests/in-memory-department-tests.bal
ballerina/tests/in-memory-employee-tests.bal
ballerina/tests/in-memory-workspace-tests.bal
ballerina/tests/in_memory_rainer_generated_client.bal
ballerina/tests/in_memory_test_entities_generated_client.bal
ballerina/tests/sql-all-types-tests.bal
ballerina/tests/sql-building-tests.bal
ballerina/tests/sql-composite-key-tests.bal
ballerina/tests/sql-department-tests.bal
ballerina/tests/sql-employee-tests.bal
ballerina/tests/sql-transaction-tests.bal
ballerina/tests/sql-workspace-tests.bal
ballerina/utils.bal
examples/medical-center/README.md

Update error types for google sheets client

---

ballerina/googlesheets_client.bal

Update code changing the order of checking time types

---

gradle.properties

Remove duplicated dependancies in the repository

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties

Update the dependency versions for Swan Lake Update 6

---

ballerina/stream_types.bal
ballerina/tests/init-tests.bal
ballerina/utils.bal

Update PersistGoogleSheetsStream with persist:Error

---

ballerina/stream_types.bal
ballerina/utils.bal
native/src/main/java/module-info.java

Make convertToArray util method public and move close entity stream

---

ballerina/utils.bal

Make convertToArray method to public

---

README.md
ballerina/Dependencies.toml
ballerina/Module.md
ballerina/Package.md
docs/spec/spec.md

Update documentation to be consistent with the new design

---

ballerina/Dependencies.toml
compiler-plugin-test/src/test/java/io/ballerina/stdlib/persist/compiler/CodeActionTest.java
compiler-plugin-test/src/test/java/io/ballerina/stdlib/persist/compiler/CompilerPluginTest.java

Disable failing tests due to the usages of 'ballerinax-mysql'

---

compiler-plugin-test/src/test/java/io/ballerina/stdlib/persist/compiler/CodeActionTest.java
compiler-plugin-test/src/test/java/io/ballerina/stdlib/persist/compiler/CompilerPluginTest.java

Enable disabled tests

---

ballerina/Dependencies.toml
codecov.yml
native/src/main/java/io/ballerina/stdlib/persist/ErrorGenerator.java

$subject
Related issue: https://github.com/ballerina-platform/ballerina-standard-library/issues/4613

Add Util functions to improve usage of runtime.invokeMethodAsynchronously

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
native/src/main/java/io/ballerina/stdlib/persist/plural/Pluralizer.java
native/src/main/java/io/ballerina/stdlib/persist/plural/Rules.java
native/src/main/java/module-info.java

Move plural implementation from persist-tool

---

native/src/main/java/io/ballerina/stdlib/persist/plural/Pluralizer.java
native/src/main/java/io/ballerina/stdlib/persist/plural/Rules.java

Sync Java 17 changes with main

---

.github/workflows/build-timestamped-master.yml
.github/workflows/central-publish.yml
.github/workflows/publish-release.yml
.github/workflows/publish-snapshot-nexus.yml
.github/workflows/pull-request.yml
.github/workflows/trivy-scan.yml

Update java-version to 17.0.7

---

.github/workflows/pull-request.yml

Inherit secrets for codecov

---

.github/workflows/publish-snapshot-nexus.yml
native/build.gradle

Change configs as per standard

---

.github/workflows/publish-snapshot-nexus.yml

Fix publish snapshot config

---

compiler-plugin/build.gradle

Publish persist-compiler-plugin jar to github packages

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
changelog.md
compiler-plugin-test/src/test/java/io/ballerina/stdlib/persist/compiler/CompilerPluginTest.java
compiler-plugin-test/src/test/resources/project_2/Ballerina.toml
compiler-plugin-test/src/test/resources/project_3/Ballerina.toml
compiler-plugin-test/src/test/resources/project_4/Ballerina.toml
compiler-plugin-test/src/test/resources/project_5/Ballerina.toml
compiler-plugin-test/src/test/resources/project_6/Ballerina.toml
compiler-plugin-test/src/test/resources/project_7/Ballerina.toml
compiler-plugin-test/src/test/resources/project_7/persist/field-types.bal
compiler-plugin-test/src/test/resources/project_7/target/Persist.toml
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/Constants.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/utils/Utils.java
gradle.properties

Add validation support for new generate command

---

ballerina/Ballerina.toml
build-config/resources/Ballerina.toml

Update Ballerina distribution version

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
changelog.md
compiler-plugin-test/src/test/java/io/ballerina/stdlib/persist/compiler/CompilerPluginTest.java
compiler-plugin-test/src/test/resources/project_11/Ballerina.toml
compiler-plugin-test/src/test/resources/project_11/persist/field-types.bal
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/Constants.java
compiler-plugin/src/main/java/io/ballerina/stdlib/persist/compiler/utils/ValidatorsByDatastore.java
gradle.properties

Related issue: https://github.com/ballerina-platform/ballerina-library/issues/5715

Add H2 database to the persist model validation

---

ballerina/Ballerina.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties

Prepare for the update 10 release

---

ballerina/Dependencies.toml
gradle.properties

Update the lang version

---

ballerina/Ballerina.toml
ballerina/CompilerPlugin.toml
ballerina/Dependencies.toml
build-config/resources/Ballerina.toml
gradle.properties

Update dependency versions for Update 11
